DATABASE_NAME = 'DATABASE_NAME'
DATABASE_USER = 'DATABASE_USER'
DATABASE_HOST = 'DATABASE_HOST'
DATABASE_PASSWORD = 'DATABASE_PASSWORD'
DATABASE_STRING_FORM = "postgresql://{}:{}@{}:5432/{}"
DATABASE_STRING = DATABASE_STRING_FORM.format(DATABASE_USER, DATABASE_PASSWORD,
                                              DATABASE_HOST, DATABASE_NAME)

def getDatabaseString():
    return DATABASE_STRING